[package]
name = "kernel"
version = "0.1.32"
build = "build.rs"

[lib]
name = "kernel"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
alloc_kernel = { path = "alloc_kernel" }
bitflags = "1"
spin = "0.4"
raw-cpuid = "3.0"
redox_syscall = { path = "syscall" }

[dependencies.goblin]
version = "0.0.10"
default-features = false
features = ["elf32", "elf64"]

[dependencies.x86]
version = "0.7"
default-features = false

[features]
default = []
doc = []
live = []
multi_core = []
