[package]
name = "kernel"
version = "0.1.0"

[lib]
name = "kernel"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
bitflags = "*"
spin = "*"
redox_syscall = { git = "https://github.com/redox-os/syscall.git" }

[dependencies.goblin]
git = "https://github.com/m4b/goblin.git"
default-features = false
features = ["elf32", "elf64"]

[dev-dependencies]
arch_test = { path = "arch/test" }

[target.'cfg(target_arch = "arm")'.dependencies]
arch_arm = { path = "arch/arm" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
arch_x86_64 = { path = "arch/x86_64" }

[features]
default = []
live = []
