[package]
name = "arch_x86_64"
version = "0.1.0"

[dependencies]
alloc_kernel = { path = "../../alloc_kernel/" }
bitflags = "0.7"
raw-cpuid = "2.0"
spin = "0.4"
redox_syscall = "0.1"

[dependencies.x86]
version = "0.7"
default-features = false
