[package]
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
name = "alloc_kernel"
version = "0.1.0"

[dependencies]
linked_list_allocator = { git = "https://github.com/phil-opp/linked-list-allocator.git" }
spin = "*"
